// kitchen-sink/react-ts/src/Rappid.tsx
import { useRef, useEffect } from 'react';
import jointjsLogo from '/assets/icons/joint-js.svg';

import { StencilService } from './services/stencil-service';
import { ToolbarService } from './services/toolbar-service';
import { InspectorService } from './services/inspector-service';
import { HaloService } from './services/halo-service';
import { KeyboardService } from './services/keyboard-service';
import { NavigatorService } from './services/navigator-service';
import RappidService from './services/kitchensink-service';

import { sampleGraphs } from './config/sample-graphs';

function Rappid() {
    const rappid = useRef<RappidService>(null);
    const elementRef = useRef<HTMLDivElement>(null);

    // Containers
    const paperContainer = useRef<HTMLDivElement>(null);
    const stencilContainer = useRef<HTMLDivElement>(null);
    const toolbarContainer = useRef<HTMLDivElement>(null);
    const inspectorContainer = useRef<HTMLDivElement>(null);
    const navigatorContainer = useRef<HTMLDivElement>(null);

    // Additional inspector elements
    const openGroupsButton = useRef<HTMLButtonElement>(null);
    const closeGroupsButton = useRef<HTMLButtonElement>(null);
    const inspectorHeader = useRef<HTMLDivElement>(null);
    const inspectorContent = useRef<HTMLDivElement>(null);

    useEffect(() => {
        const services = {
            stencilService: new StencilService(stencilContainer.current),
            toolbarService: new ToolbarService(toolbarContainer.current),
            inspectorService: new InspectorService({
                openGroupsButton: openGroupsButton.current,
                closeGroupsButton: closeGroupsButton.current,
                container: inspectorContainer.current,
                header: inspectorHeader.current,
                content: inspectorContent.current,
            }),
            haloService: new HaloService(),
            keyboardService: new KeyboardService(),
            navigatorService: new NavigatorService(navigatorContainer.current),
        };

        rappid.current = new RappidService(
            elementRef.current!,
            paperContainer.current!,
            services
        );

        rappid.current.startRappid();

        rappid.current.graph.fromJSON(
            JSON.parse(sampleGraphs.emergencyProcedure),
            { ignoreUndoRedo: true }
        );
    }, []);

    return (
        <div id="app" className="joint-app">
            <div className="app-header">
                <img src={jointjsLogo} alt="JointJS" />
            </div>
            <div ref={toolbarContainer} className="toolbar-container"></div>
            <div className="app-body">
                <div ref={stencilContainer} className="stencil-container"></div>
                <div ref={paperContainer} className="paper-container"></div>
                <div ref={inspectorContainer} className="inspector-container">
                    <div
                        ref={inspectorHeader}
                        className="inspector-header hidden"
                    >
                        <button
                            ref={openGroupsButton}
                            className="open-groups-btn"
                        ></button>
                        <button
                            ref={closeGroupsButton}
                            className="close-groups-btn"
                        ></button>
                        <span className="inspector-header-text">
                            Properties
                        </span>
                    </div>
                    <div
                        ref={inspectorContent}
                        className="inspector-content"
                    ></div>
                </div>
                <div
                    ref={navigatorContainer}
                    className="navigator-container"
                ></div>
            </div>
        </div>
    );
}

export default Rappid;

// kitchen-sink/vue-ts/src/Rappid.vue
<template>
  <div id="app" class="joint-app">
    <div class="app-header">
      <img src="/assets/icons/joint-js.svg" alt="JointJS" />
    </div>
    <div ref="toolbarContainer" class="toolbar-container"></div>
    <div class="app-body">
      <div ref="stencilContainer" class="stencil-container"></div>
      <div ref="paperContainer" class="paper-container"></div>
      <div ref="inspectorContainer" class="inspector-container">
        <div ref="inspectorHeader" class="inspector-header hidden">
          <button ref="openGroupsButton" class="open-groups-btn"></button>
          <button ref="closeGroupsButton" class="close-groups-btn"></button>
          <span class="inspector-header-text">Properties</span>
        </div>
        <div ref="inspectorContent" class="inspector-content"></div>
      </div>
      <div ref="navigatorContainer" class="navigator-container"></div>
    </div>
  </div>
</template>

<script lang="ts">

import { Vue, Component, Ref } from 'vue-property-decorator';

// import rappid services
import RappidService from "./services/kitchensink-service";
import { StencilService } from "./services/stencil-service";
import { ToolbarService } from "./services/toolbar-service";
import { InspectorService } from "./services/inspector-service";
import { HaloService } from "./services/halo-service";
import { KeyboardService } from "./services/keyboard-service";
import { NavigatorService } from './services/navigator-service';

import { sampleGraphs } from './config/sample-graphs';

@Component
export default class Rappid extends Vue {
  @Ref('app') readonly app!: HTMLElement
  // Containers
  @Ref('paperContainer') readonly paperContainer!: HTMLElement
  @Ref('stencilContainer') readonly stencilContainer!: HTMLElement
  @Ref('toolbarContainer') readonly toolbarContainer!: HTMLElement
  @Ref('inspectorContainer') readonly inspectorContainer!: HTMLElement
  @Ref('navigatorContainer') readonly navigatorContainer!: HTMLElement
  // Additional inspector elements
  @Ref('openGroupsButton') readonly openGroupsButton!: HTMLButtonElement
  @Ref('closeGroupsButton') readonly closeGroupsButton!: HTMLButtonElement
  @Ref('inspectorHeader') readonly inspectorHeader!: HTMLDivElement
  @Ref('inspectorContent') readonly inspectorContent!: HTMLElement

  rappid: RappidService;

  mounted() {
    const services = {
      stencilService: new StencilService(this.stencilContainer),
      toolbarService: new ToolbarService(this.toolbarContainer),
      inspectorService: new InspectorService({
        openGroupsButton: this.openGroupsButton,
        closeGroupsButton: this.closeGroupsButton,
        container: this.inspectorContainer,
        header: this.inspectorHeader,
        content: this.inspectorContent
      }),
      haloService: new HaloService(),
      keyboardService: new KeyboardService(),
      navigatorService: new NavigatorService(this.navigatorContainer)
    }

    this.rappid = new RappidService(
      this.app,
      this.paperContainer,
      services
    );

    this.rappid.startRappid();

    this.rappid.graph.fromJSON(JSON.parse(sampleGraphs.emergencyProcedure), { ignoreUndoRedo: true });
  }
}
</script>

<style lang="scss">
// import rappid styles
@import "~@joint/plus/joint-plus.css";
// import custom styles
@import "../css/styles";
</style>
