// chatbot/react-redux-ts/src/components/Chatbot/Inspector/MessageInspector.tsx
import React, { ChangeEvent, ReactElement, useCallback, useState } from 'react';
import { shapes } from '@joint/plus';

import { useBaseInspector } from './useBaseInspector';
import Input from '../Input/Input';

interface Props {
    cell: shapes.app.Message;
}

interface InspectorPort {
    id: string;
    label: string;
}

const cellProps = {
    label: ['attrs', 'label', 'text'],
    description: ['attrs', 'description', 'text'],
    icon: ['attrs', 'icon', 'xlinkHref'],
    portLabel: ['attrs', 'portLabel', 'text']
};

const MessageInspector = (props: Props): ReactElement => {

    const { cell } = props;

    const [label, setLabel] = useState<string>('');
    const [description, setDescription] = useState<string>('');
    const [icon, setIcon] = useState<string>('');
    const [ports, setPorts] = useState<InspectorPort[]>([]);
    const [canAddPort, setCanAddPort] = useState<boolean>(false);

    const assignFormPorts = useCallback((): void => {
        setCanAddPort(cell.canAddPort('out'));
        setPorts(cell.getGroupPorts('out').map(({ id }) => {
            return {
                id,
                label: cell.portProp(id, cellProps.portLabel)
            };
        }));
    }, [cell]);

    const assignFormFields = useCallback((): void => {
        setLabel(cell.prop(cellProps.label));
        setDescription(cell.prop(cellProps.description));
        setIcon(cell.prop(cellProps.icon));
        assignFormPorts();
    }, [cell, assignFormPorts]);

    const changeCellProp = useBaseInspector({ cell, assignFormFields });

    const addCellPort = (): void => {
        cell.addDefaultPort();
        assignFormPorts();
    };

    const removeCellPort = (portId: string): void => {
        cell.removePort(portId);
        assignFormPorts();
    };

    const changeCellPort = (port: InspectorPort, value: string): void => {
        cell.portProp(port.id, cellProps.portLabel, value);
    };

    return (
        <>
            <h1>Component</h1>

            <label>Label
                <Input type="text"
                       placeholder="Enter label"
                       value={label}
                       onChange={(e: ChangeEvent<HTMLInputElement>) => changeCellProp(cellProps.label, e.target.value)}
                />
            </label>

            <label>Description
                <Input type="text"
                       placeholder="Enter description"
                       value={description}
                       onChange={(e: ChangeEvent<HTMLInputElement>) => changeCellProp(cellProps.description, e.target.value)}
                />
            </label>

            <label>Icon (Base64)
            <span className="icon-input-logo"/>
                <Input className="icon-input"
                       type="text"
                       placeholder="Enter icon"
                       value={icon}
                       spellCheck={false}
                       onChange={(e: ChangeEvent<HTMLInputElement>) => changeCellProp(cellProps.icon, e.target.value)}
                />
            </label>

            <div className="ports">
                <div className="out-ports-bar">
                    <span>Out Ports</span>
                    <button disabled={!canAddPort}
                            onClick={addCellPort}
                            className="add-port"
                            data-tooltip="Add Output Port">
                    </button>
                </div>
                {ports.map(port => {
                    return (
                        <div key={port.id} className="port">
                            <Input defaultValue={port.label}
                                   onChange={(e: ChangeEvent<HTMLInputElement>) => changeCellPort(port, e.target.value)}
                            />
                            <button className="remove-port"
                                    onClick={() => removeCellPort(port.id)}
                                    data-tooltip="Remove Output Port">
                            </button>
                        </div>
                    );
                })}
            </div>
        </>
    );
};

export default MessageInspector;

// chatbot/angular/src/app/inspector/message-inspector/message-inspector.component.ts
/*! JointJS+ v4.2.2 (2026-01-22) - HTML5 Diagramming Framework

Copyright (c) 2025 client IO

This Source Code Form is subject to the terms of the JointJS+
License, v. 2.0. If a copy of the JointJS+ License was not
distributed with this file, You can obtain one at
https://www.jointjs.com/license or from the JointJS+ archive as was
distributed by client IO. See the LICENSE file.
*/

import { Component, Input } from '@angular/core';
import type { shapes } from '@joint/plus';

import { BaseInspectorComponent } from '../base-inspector/base-inspector.component';

interface InspectorPort {
    id: string;
    label: string;
}

@Component({
    selector: 'app-message-inspector',
    templateUrl: './message-inspector.component.html',
    styleUrls: ['../inspector.component.scss']
})
export class MessageInspectorComponent extends BaseInspectorComponent {

    @Input() cell: shapes.app.Message = null;

    public label: string;
    public description: string;
    public icon: string;
    public ports: InspectorPort[];
    public canAddPort = false;

    public props = {
        label: ['attrs', 'label', 'text'],
        description: ['attrs', 'description', 'text'],
        icon: ['attrs', 'icon', 'xlinkHref'],
        portLabel: ['attrs', 'portLabel', 'text']
    };

    public addCellPort(): void {
        this.cell.addDefaultPort();
        this.assignFormPorts();
    }

    public removeCellPort(portId: string): void {
        this.cell.removePort(portId);
        this.assignFormPorts();
    }

    public changeCellPort(port: InspectorPort): void {
        const { cell, props } = this;
        cell.portProp(port.id, props.portLabel, port.label);
    }

    public trackByPortId(index: number, port: InspectorPort): string {
        return port.id;
    }

    protected assignFormFields(): void {
        const { cell, props } = this;
        this.label = cell.prop(props.label);
        this.description = cell.prop(props.description);
        this.icon = cell.prop(props.icon);
        this.assignFormPorts();
    }

    private assignFormPorts(): void {
        const { cell, props } = this;
        this.canAddPort = cell.canAddPort('out');
        this.ports = cell.getGroupPorts('out').map(({ id }) => {
            return {
                id,
                label: cell.portProp(id, props.portLabel)
            };
        });
    }
}
